# Highway
HW_IMAGE_HEIGHT = 64
HW_IMAGE_WIDTH = 128
VEHICLE_COUNT = 10
ENV_FEATURES_SIZE = 7

# Cart Pole
CP_IMAGE_HEIGHT = 40  # 400
CP_IMAGE_WIDTH = 60  # 600
CP_ACTION_SPACE = 2
CP_OBS_SPACE = 4
CP_INPUT_SIZE = CP_ACTION_SPACE * CP_OBS_SPACE

